// Code generated by ent, DO NOT EDIT.

package edge

import (
	"entgo.io/ent/dialect/sql"
	"github.com/TSELab/astra/internal/store/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Edge {
	return predicate.Edge(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Edge {
	return predicate.Edge(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Edge {
	return predicate.Edge(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Edge {
	return predicate.Edge(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Edge {
	return predicate.Edge(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Edge {
	return predicate.Edge(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Edge {
	return predicate.Edge(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Edge {
	return predicate.Edge(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Edge {
	return predicate.Edge(sql.FieldLTE(FieldID, id))
}

// Source applies equality check predicate on the "source" field. It's identical to SourceEQ.
func Source(v string) predicate.Edge {
	return predicate.Edge(sql.FieldEQ(FieldSource, v))
}

// Target applies equality check predicate on the "target" field. It's identical to TargetEQ.
func Target(v string) predicate.Edge {
	return predicate.Edge(sql.FieldEQ(FieldTarget, v))
}

// Relation applies equality check predicate on the "relation" field. It's identical to RelationEQ.
func Relation(v string) predicate.Edge {
	return predicate.Edge(sql.FieldEQ(FieldRelation, v))
}

// SourceEQ applies the EQ predicate on the "source" field.
func SourceEQ(v string) predicate.Edge {
	return predicate.Edge(sql.FieldEQ(FieldSource, v))
}

// SourceNEQ applies the NEQ predicate on the "source" field.
func SourceNEQ(v string) predicate.Edge {
	return predicate.Edge(sql.FieldNEQ(FieldSource, v))
}

// SourceIn applies the In predicate on the "source" field.
func SourceIn(vs ...string) predicate.Edge {
	return predicate.Edge(sql.FieldIn(FieldSource, vs...))
}

// SourceNotIn applies the NotIn predicate on the "source" field.
func SourceNotIn(vs ...string) predicate.Edge {
	return predicate.Edge(sql.FieldNotIn(FieldSource, vs...))
}

// SourceGT applies the GT predicate on the "source" field.
func SourceGT(v string) predicate.Edge {
	return predicate.Edge(sql.FieldGT(FieldSource, v))
}

// SourceGTE applies the GTE predicate on the "source" field.
func SourceGTE(v string) predicate.Edge {
	return predicate.Edge(sql.FieldGTE(FieldSource, v))
}

// SourceLT applies the LT predicate on the "source" field.
func SourceLT(v string) predicate.Edge {
	return predicate.Edge(sql.FieldLT(FieldSource, v))
}

// SourceLTE applies the LTE predicate on the "source" field.
func SourceLTE(v string) predicate.Edge {
	return predicate.Edge(sql.FieldLTE(FieldSource, v))
}

// SourceContains applies the Contains predicate on the "source" field.
func SourceContains(v string) predicate.Edge {
	return predicate.Edge(sql.FieldContains(FieldSource, v))
}

// SourceHasPrefix applies the HasPrefix predicate on the "source" field.
func SourceHasPrefix(v string) predicate.Edge {
	return predicate.Edge(sql.FieldHasPrefix(FieldSource, v))
}

// SourceHasSuffix applies the HasSuffix predicate on the "source" field.
func SourceHasSuffix(v string) predicate.Edge {
	return predicate.Edge(sql.FieldHasSuffix(FieldSource, v))
}

// SourceEqualFold applies the EqualFold predicate on the "source" field.
func SourceEqualFold(v string) predicate.Edge {
	return predicate.Edge(sql.FieldEqualFold(FieldSource, v))
}

// SourceContainsFold applies the ContainsFold predicate on the "source" field.
func SourceContainsFold(v string) predicate.Edge {
	return predicate.Edge(sql.FieldContainsFold(FieldSource, v))
}

// TargetEQ applies the EQ predicate on the "target" field.
func TargetEQ(v string) predicate.Edge {
	return predicate.Edge(sql.FieldEQ(FieldTarget, v))
}

// TargetNEQ applies the NEQ predicate on the "target" field.
func TargetNEQ(v string) predicate.Edge {
	return predicate.Edge(sql.FieldNEQ(FieldTarget, v))
}

// TargetIn applies the In predicate on the "target" field.
func TargetIn(vs ...string) predicate.Edge {
	return predicate.Edge(sql.FieldIn(FieldTarget, vs...))
}

// TargetNotIn applies the NotIn predicate on the "target" field.
func TargetNotIn(vs ...string) predicate.Edge {
	return predicate.Edge(sql.FieldNotIn(FieldTarget, vs...))
}

// TargetGT applies the GT predicate on the "target" field.
func TargetGT(v string) predicate.Edge {
	return predicate.Edge(sql.FieldGT(FieldTarget, v))
}

// TargetGTE applies the GTE predicate on the "target" field.
func TargetGTE(v string) predicate.Edge {
	return predicate.Edge(sql.FieldGTE(FieldTarget, v))
}

// TargetLT applies the LT predicate on the "target" field.
func TargetLT(v string) predicate.Edge {
	return predicate.Edge(sql.FieldLT(FieldTarget, v))
}

// TargetLTE applies the LTE predicate on the "target" field.
func TargetLTE(v string) predicate.Edge {
	return predicate.Edge(sql.FieldLTE(FieldTarget, v))
}

// TargetContains applies the Contains predicate on the "target" field.
func TargetContains(v string) predicate.Edge {
	return predicate.Edge(sql.FieldContains(FieldTarget, v))
}

// TargetHasPrefix applies the HasPrefix predicate on the "target" field.
func TargetHasPrefix(v string) predicate.Edge {
	return predicate.Edge(sql.FieldHasPrefix(FieldTarget, v))
}

// TargetHasSuffix applies the HasSuffix predicate on the "target" field.
func TargetHasSuffix(v string) predicate.Edge {
	return predicate.Edge(sql.FieldHasSuffix(FieldTarget, v))
}

// TargetEqualFold applies the EqualFold predicate on the "target" field.
func TargetEqualFold(v string) predicate.Edge {
	return predicate.Edge(sql.FieldEqualFold(FieldTarget, v))
}

// TargetContainsFold applies the ContainsFold predicate on the "target" field.
func TargetContainsFold(v string) predicate.Edge {
	return predicate.Edge(sql.FieldContainsFold(FieldTarget, v))
}

// RelationEQ applies the EQ predicate on the "relation" field.
func RelationEQ(v string) predicate.Edge {
	return predicate.Edge(sql.FieldEQ(FieldRelation, v))
}

// RelationNEQ applies the NEQ predicate on the "relation" field.
func RelationNEQ(v string) predicate.Edge {
	return predicate.Edge(sql.FieldNEQ(FieldRelation, v))
}

// RelationIn applies the In predicate on the "relation" field.
func RelationIn(vs ...string) predicate.Edge {
	return predicate.Edge(sql.FieldIn(FieldRelation, vs...))
}

// RelationNotIn applies the NotIn predicate on the "relation" field.
func RelationNotIn(vs ...string) predicate.Edge {
	return predicate.Edge(sql.FieldNotIn(FieldRelation, vs...))
}

// RelationGT applies the GT predicate on the "relation" field.
func RelationGT(v string) predicate.Edge {
	return predicate.Edge(sql.FieldGT(FieldRelation, v))
}

// RelationGTE applies the GTE predicate on the "relation" field.
func RelationGTE(v string) predicate.Edge {
	return predicate.Edge(sql.FieldGTE(FieldRelation, v))
}

// RelationLT applies the LT predicate on the "relation" field.
func RelationLT(v string) predicate.Edge {
	return predicate.Edge(sql.FieldLT(FieldRelation, v))
}

// RelationLTE applies the LTE predicate on the "relation" field.
func RelationLTE(v string) predicate.Edge {
	return predicate.Edge(sql.FieldLTE(FieldRelation, v))
}

// RelationContains applies the Contains predicate on the "relation" field.
func RelationContains(v string) predicate.Edge {
	return predicate.Edge(sql.FieldContains(FieldRelation, v))
}

// RelationHasPrefix applies the HasPrefix predicate on the "relation" field.
func RelationHasPrefix(v string) predicate.Edge {
	return predicate.Edge(sql.FieldHasPrefix(FieldRelation, v))
}

// RelationHasSuffix applies the HasSuffix predicate on the "relation" field.
func RelationHasSuffix(v string) predicate.Edge {
	return predicate.Edge(sql.FieldHasSuffix(FieldRelation, v))
}

// RelationEqualFold applies the EqualFold predicate on the "relation" field.
func RelationEqualFold(v string) predicate.Edge {
	return predicate.Edge(sql.FieldEqualFold(FieldRelation, v))
}

// RelationContainsFold applies the ContainsFold predicate on the "relation" field.
func RelationContainsFold(v string) predicate.Edge {
	return predicate.Edge(sql.FieldContainsFold(FieldRelation, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Edge) predicate.Edge {
	return predicate.Edge(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Edge) predicate.Edge {
	return predicate.Edge(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Edge) predicate.Edge {
	return predicate.Edge(sql.NotPredicates(p))
}
