// Code generated by ent, DO NOT EDIT.

package step

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the step type in the database.
	Label = "step"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldAstraID holds the string denoting the astra_id field in the database.
	FieldAstraID = "astra_id"
	// FieldCommand holds the string denoting the command field in the database.
	FieldCommand = "command"
	// FieldEnvironment holds the string denoting the environment field in the database.
	FieldEnvironment = "environment"
	// FieldArch holds the string denoting the arch field in the database.
	FieldArch = "arch"
	// FieldTimestamp holds the string denoting the timestamp field in the database.
	FieldTimestamp = "timestamp"
	// FieldMetadata holds the string denoting the metadata field in the database.
	FieldMetadata = "metadata"
	// FieldCompleteness holds the string denoting the completeness field in the database.
	FieldCompleteness = "completeness"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// Table holds the table name of the step in the database.
	Table = "steps"
)

// Columns holds all SQL columns for step fields.
var Columns = []string{
	FieldID,
	FieldAstraID,
	FieldCommand,
	FieldEnvironment,
	FieldArch,
	FieldTimestamp,
	FieldMetadata,
	FieldCompleteness,
	FieldCreatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// AstraIDValidator is a validator for the "astra_id" field. It is called by the builders before save.
	AstraIDValidator func(string) error
	// DefaultCommand holds the default value on creation for the "command" field.
	DefaultCommand string
	// DefaultArch holds the default value on creation for the "Arch" field.
	DefaultArch string
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
)

// Completeness defines the type for the "completeness" enum field.
type Completeness string

// CompletenessComplete is the default value of the Completeness enum.
const DefaultCompleteness = CompletenessComplete

// Completeness values.
const (
	CompletenessComplete   Completeness = "complete"
	CompletenessIncomplete Completeness = "incomplete"
)

func (c Completeness) String() string {
	return string(c)
}

// CompletenessValidator is a validator for the "completeness" field enum values. It is called by the builders before save.
func CompletenessValidator(c Completeness) error {
	switch c {
	case CompletenessComplete, CompletenessIncomplete:
		return nil
	default:
		return fmt.Errorf("step: invalid enum value for completeness field: %q", c)
	}
}

// OrderOption defines the ordering options for the Step queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByAstraID orders the results by the astra_id field.
func ByAstraID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAstraID, opts...).ToFunc()
}

// ByCommand orders the results by the command field.
func ByCommand(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCommand, opts...).ToFunc()
}

// ByArch orders the results by the Arch field.
func ByArch(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldArch, opts...).ToFunc()
}

// ByTimestamp orders the results by the timestamp field.
func ByTimestamp(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTimestamp, opts...).ToFunc()
}

// ByCompleteness orders the results by the completeness field.
func ByCompleteness(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCompleteness, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}
