// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/TSELab/astra/internal/store/ent/edge"
)

// EdgeCreate is the builder for creating a Edge entity.
type EdgeCreate struct {
	config
	mutation *EdgeMutation
	hooks    []Hook
}

// SetSource sets the "source" field.
func (_c *EdgeCreate) SetSource(v string) *EdgeCreate {
	_c.mutation.SetSource(v)
	return _c
}

// SetTarget sets the "target" field.
func (_c *EdgeCreate) SetTarget(v string) *EdgeCreate {
	_c.mutation.SetTarget(v)
	return _c
}

// SetRelation sets the "relation" field.
func (_c *EdgeCreate) SetRelation(v string) *EdgeCreate {
	_c.mutation.SetRelation(v)
	return _c
}

// Mutation returns the EdgeMutation object of the builder.
func (_c *EdgeCreate) Mutation() *EdgeMutation {
	return _c.mutation
}

// Save creates the Edge in the database.
func (_c *EdgeCreate) Save(ctx context.Context) (*Edge, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *EdgeCreate) SaveX(ctx context.Context) *Edge {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *EdgeCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *EdgeCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *EdgeCreate) check() error {
	if _, ok := _c.mutation.Source(); !ok {
		return &ValidationError{Name: "source", err: errors.New(`ent: missing required field "Edge.source"`)}
	}
	if _, ok := _c.mutation.Target(); !ok {
		return &ValidationError{Name: "target", err: errors.New(`ent: missing required field "Edge.target"`)}
	}
	if _, ok := _c.mutation.Relation(); !ok {
		return &ValidationError{Name: "relation", err: errors.New(`ent: missing required field "Edge.relation"`)}
	}
	return nil
}

func (_c *EdgeCreate) sqlSave(ctx context.Context) (*Edge, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *EdgeCreate) createSpec() (*Edge, *sqlgraph.CreateSpec) {
	var (
		_node = &Edge{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(edge.Table, sqlgraph.NewFieldSpec(edge.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Source(); ok {
		_spec.SetField(edge.FieldSource, field.TypeString, value)
		_node.Source = value
	}
	if value, ok := _c.mutation.Target(); ok {
		_spec.SetField(edge.FieldTarget, field.TypeString, value)
		_node.Target = value
	}
	if value, ok := _c.mutation.Relation(); ok {
		_spec.SetField(edge.FieldRelation, field.TypeString, value)
		_node.Relation = value
	}
	return _node, _spec
}

// EdgeCreateBulk is the builder for creating many Edge entities in bulk.
type EdgeCreateBulk struct {
	config
	err      error
	builders []*EdgeCreate
}

// Save creates the Edge entities in the database.
func (_c *EdgeCreateBulk) Save(ctx context.Context) ([]*Edge, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Edge, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*EdgeMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *EdgeCreateBulk) SaveX(ctx context.Context) []*Edge {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *EdgeCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *EdgeCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
