// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/TSELab/astra/internal/store/ent/principal"
)

// Principal is the model entity for the Principal schema.
type Principal struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// unique AStRA principal ID
	AstraID string `json:"astra_id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Trust holds the value of the "trust" field.
	Trust string `json:"trust,omitempty"`
	// Builder holds the value of the "builder" field.
	Builder string `json:"builder,omitempty"`
	// Metadata holds the value of the "metadata" field.
	Metadata map[string]string `json:"metadata,omitempty"`
	// Completeness holds the value of the "completeness" field.
	Completeness principal.Completeness `json:"completeness,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt    time.Time `json:"created_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Principal) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case principal.FieldMetadata:
			values[i] = new([]byte)
		case principal.FieldID:
			values[i] = new(sql.NullInt64)
		case principal.FieldAstraID, principal.FieldName, principal.FieldTrust, principal.FieldBuilder, principal.FieldCompleteness:
			values[i] = new(sql.NullString)
		case principal.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Principal fields.
func (_m *Principal) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case principal.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case principal.FieldAstraID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field astra_id", values[i])
			} else if value.Valid {
				_m.AstraID = value.String
			}
		case principal.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case principal.FieldTrust:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field trust", values[i])
			} else if value.Valid {
				_m.Trust = value.String
			}
		case principal.FieldBuilder:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field builder", values[i])
			} else if value.Valid {
				_m.Builder = value.String
			}
		case principal.FieldMetadata:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field metadata", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Metadata); err != nil {
					return fmt.Errorf("unmarshal field metadata: %w", err)
				}
			}
		case principal.FieldCompleteness:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field completeness", values[i])
			} else if value.Valid {
				_m.Completeness = principal.Completeness(value.String)
			}
		case principal.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Principal.
// This includes values selected through modifiers, order, etc.
func (_m *Principal) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this Principal.
// Note that you need to call Principal.Unwrap() before calling this method if this Principal
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Principal) Update() *PrincipalUpdateOne {
	return NewPrincipalClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Principal entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Principal) Unwrap() *Principal {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Principal is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Principal) String() string {
	var builder strings.Builder
	builder.WriteString("Principal(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("astra_id=")
	builder.WriteString(_m.AstraID)
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("trust=")
	builder.WriteString(_m.Trust)
	builder.WriteString(", ")
	builder.WriteString("builder=")
	builder.WriteString(_m.Builder)
	builder.WriteString(", ")
	builder.WriteString("metadata=")
	builder.WriteString(fmt.Sprintf("%v", _m.Metadata))
	builder.WriteString(", ")
	builder.WriteString("completeness=")
	builder.WriteString(fmt.Sprintf("%v", _m.Completeness))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Principals is a parsable slice of Principal.
type Principals []*Principal
