// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/TSELab/astra/internal/store/ent/principal"
)

// PrincipalCreate is the builder for creating a Principal entity.
type PrincipalCreate struct {
	config
	mutation *PrincipalMutation
	hooks    []Hook
}

// SetAstraID sets the "astra_id" field.
func (_c *PrincipalCreate) SetAstraID(v string) *PrincipalCreate {
	_c.mutation.SetAstraID(v)
	return _c
}

// SetName sets the "name" field.
func (_c *PrincipalCreate) SetName(v string) *PrincipalCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_c *PrincipalCreate) SetNillableName(v *string) *PrincipalCreate {
	if v != nil {
		_c.SetName(*v)
	}
	return _c
}

// SetTrust sets the "trust" field.
func (_c *PrincipalCreate) SetTrust(v string) *PrincipalCreate {
	_c.mutation.SetTrust(v)
	return _c
}

// SetNillableTrust sets the "trust" field if the given value is not nil.
func (_c *PrincipalCreate) SetNillableTrust(v *string) *PrincipalCreate {
	if v != nil {
		_c.SetTrust(*v)
	}
	return _c
}

// SetBuilder sets the "builder" field.
func (_c *PrincipalCreate) SetBuilder(v string) *PrincipalCreate {
	_c.mutation.SetBuilder(v)
	return _c
}

// SetNillableBuilder sets the "builder" field if the given value is not nil.
func (_c *PrincipalCreate) SetNillableBuilder(v *string) *PrincipalCreate {
	if v != nil {
		_c.SetBuilder(*v)
	}
	return _c
}

// SetMetadata sets the "metadata" field.
func (_c *PrincipalCreate) SetMetadata(v map[string]string) *PrincipalCreate {
	_c.mutation.SetMetadata(v)
	return _c
}

// SetCompleteness sets the "completeness" field.
func (_c *PrincipalCreate) SetCompleteness(v principal.Completeness) *PrincipalCreate {
	_c.mutation.SetCompleteness(v)
	return _c
}

// SetNillableCompleteness sets the "completeness" field if the given value is not nil.
func (_c *PrincipalCreate) SetNillableCompleteness(v *principal.Completeness) *PrincipalCreate {
	if v != nil {
		_c.SetCompleteness(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *PrincipalCreate) SetCreatedAt(v time.Time) *PrincipalCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *PrincipalCreate) SetNillableCreatedAt(v *time.Time) *PrincipalCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// Mutation returns the PrincipalMutation object of the builder.
func (_c *PrincipalCreate) Mutation() *PrincipalMutation {
	return _c.mutation
}

// Save creates the Principal in the database.
func (_c *PrincipalCreate) Save(ctx context.Context) (*Principal, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *PrincipalCreate) SaveX(ctx context.Context) *Principal {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PrincipalCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PrincipalCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *PrincipalCreate) defaults() {
	if _, ok := _c.mutation.Name(); !ok {
		v := principal.DefaultName
		_c.mutation.SetName(v)
	}
	if _, ok := _c.mutation.Trust(); !ok {
		v := principal.DefaultTrust
		_c.mutation.SetTrust(v)
	}
	if _, ok := _c.mutation.Builder(); !ok {
		v := principal.DefaultBuilder
		_c.mutation.SetBuilder(v)
	}
	if _, ok := _c.mutation.Completeness(); !ok {
		v := principal.DefaultCompleteness
		_c.mutation.SetCompleteness(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := principal.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *PrincipalCreate) check() error {
	if _, ok := _c.mutation.AstraID(); !ok {
		return &ValidationError{Name: "astra_id", err: errors.New(`ent: missing required field "Principal.astra_id"`)}
	}
	if v, ok := _c.mutation.AstraID(); ok {
		if err := principal.AstraIDValidator(v); err != nil {
			return &ValidationError{Name: "astra_id", err: fmt.Errorf(`ent: validator failed for field "Principal.astra_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Principal.name"`)}
	}
	if _, ok := _c.mutation.Trust(); !ok {
		return &ValidationError{Name: "trust", err: errors.New(`ent: missing required field "Principal.trust"`)}
	}
	if _, ok := _c.mutation.Builder(); !ok {
		return &ValidationError{Name: "builder", err: errors.New(`ent: missing required field "Principal.builder"`)}
	}
	if _, ok := _c.mutation.Completeness(); !ok {
		return &ValidationError{Name: "completeness", err: errors.New(`ent: missing required field "Principal.completeness"`)}
	}
	if v, ok := _c.mutation.Completeness(); ok {
		if err := principal.CompletenessValidator(v); err != nil {
			return &ValidationError{Name: "completeness", err: fmt.Errorf(`ent: validator failed for field "Principal.completeness": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Principal.created_at"`)}
	}
	return nil
}

func (_c *PrincipalCreate) sqlSave(ctx context.Context) (*Principal, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *PrincipalCreate) createSpec() (*Principal, *sqlgraph.CreateSpec) {
	var (
		_node = &Principal{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(principal.Table, sqlgraph.NewFieldSpec(principal.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.AstraID(); ok {
		_spec.SetField(principal.FieldAstraID, field.TypeString, value)
		_node.AstraID = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(principal.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Trust(); ok {
		_spec.SetField(principal.FieldTrust, field.TypeString, value)
		_node.Trust = value
	}
	if value, ok := _c.mutation.Builder(); ok {
		_spec.SetField(principal.FieldBuilder, field.TypeString, value)
		_node.Builder = value
	}
	if value, ok := _c.mutation.Metadata(); ok {
		_spec.SetField(principal.FieldMetadata, field.TypeJSON, value)
		_node.Metadata = value
	}
	if value, ok := _c.mutation.Completeness(); ok {
		_spec.SetField(principal.FieldCompleteness, field.TypeEnum, value)
		_node.Completeness = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(principal.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	return _node, _spec
}

// PrincipalCreateBulk is the builder for creating many Principal entities in bulk.
type PrincipalCreateBulk struct {
	config
	err      error
	builders []*PrincipalCreate
}

// Save creates the Principal entities in the database.
func (_c *PrincipalCreateBulk) Save(ctx context.Context) ([]*Principal, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Principal, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*PrincipalMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *PrincipalCreateBulk) SaveX(ctx context.Context) []*Principal {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PrincipalCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PrincipalCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
