// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/TSELab/astra/internal/store/ent/resource"
)

// ResourceCreate is the builder for creating a Resource entity.
type ResourceCreate struct {
	config
	mutation *ResourceMutation
	hooks    []Hook
}

// SetAstraID sets the "astra_id" field.
func (_c *ResourceCreate) SetAstraID(v string) *ResourceCreate {
	_c.mutation.SetAstraID(v)
	return _c
}

// SetType sets the "type" field.
func (_c *ResourceCreate) SetType(v string) *ResourceCreate {
	_c.mutation.SetType(v)
	return _c
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_c *ResourceCreate) SetNillableType(v *string) *ResourceCreate {
	if v != nil {
		_c.SetType(*v)
	}
	return _c
}

// SetURI sets the "uri" field.
func (_c *ResourceCreate) SetURI(v string) *ResourceCreate {
	_c.mutation.SetURI(v)
	return _c
}

// SetNillableURI sets the "uri" field if the given value is not nil.
func (_c *ResourceCreate) SetNillableURI(v *string) *ResourceCreate {
	if v != nil {
		_c.SetURI(*v)
	}
	return _c
}

// SetFormat sets the "format" field.
func (_c *ResourceCreate) SetFormat(v string) *ResourceCreate {
	_c.mutation.SetFormat(v)
	return _c
}

// SetNillableFormat sets the "format" field if the given value is not nil.
func (_c *ResourceCreate) SetNillableFormat(v *string) *ResourceCreate {
	if v != nil {
		_c.SetFormat(*v)
	}
	return _c
}

// SetMetadata sets the "metadata" field.
func (_c *ResourceCreate) SetMetadata(v map[string]string) *ResourceCreate {
	_c.mutation.SetMetadata(v)
	return _c
}

// SetCompleteness sets the "completeness" field.
func (_c *ResourceCreate) SetCompleteness(v resource.Completeness) *ResourceCreate {
	_c.mutation.SetCompleteness(v)
	return _c
}

// SetNillableCompleteness sets the "completeness" field if the given value is not nil.
func (_c *ResourceCreate) SetNillableCompleteness(v *resource.Completeness) *ResourceCreate {
	if v != nil {
		_c.SetCompleteness(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *ResourceCreate) SetCreatedAt(v time.Time) *ResourceCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ResourceCreate) SetNillableCreatedAt(v *time.Time) *ResourceCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// Mutation returns the ResourceMutation object of the builder.
func (_c *ResourceCreate) Mutation() *ResourceMutation {
	return _c.mutation
}

// Save creates the Resource in the database.
func (_c *ResourceCreate) Save(ctx context.Context) (*Resource, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ResourceCreate) SaveX(ctx context.Context) *Resource {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ResourceCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ResourceCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ResourceCreate) defaults() {
	if _, ok := _c.mutation.GetType(); !ok {
		v := resource.DefaultType
		_c.mutation.SetType(v)
	}
	if _, ok := _c.mutation.URI(); !ok {
		v := resource.DefaultURI
		_c.mutation.SetURI(v)
	}
	if _, ok := _c.mutation.Format(); !ok {
		v := resource.DefaultFormat
		_c.mutation.SetFormat(v)
	}
	if _, ok := _c.mutation.Completeness(); !ok {
		v := resource.DefaultCompleteness
		_c.mutation.SetCompleteness(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := resource.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ResourceCreate) check() error {
	if _, ok := _c.mutation.AstraID(); !ok {
		return &ValidationError{Name: "astra_id", err: errors.New(`ent: missing required field "Resource.astra_id"`)}
	}
	if v, ok := _c.mutation.AstraID(); ok {
		if err := resource.AstraIDValidator(v); err != nil {
			return &ValidationError{Name: "astra_id", err: fmt.Errorf(`ent: validator failed for field "Resource.astra_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.GetType(); !ok {
		return &ValidationError{Name: "type", err: errors.New(`ent: missing required field "Resource.type"`)}
	}
	if _, ok := _c.mutation.URI(); !ok {
		return &ValidationError{Name: "uri", err: errors.New(`ent: missing required field "Resource.uri"`)}
	}
	if _, ok := _c.mutation.Format(); !ok {
		return &ValidationError{Name: "format", err: errors.New(`ent: missing required field "Resource.format"`)}
	}
	if _, ok := _c.mutation.Completeness(); !ok {
		return &ValidationError{Name: "completeness", err: errors.New(`ent: missing required field "Resource.completeness"`)}
	}
	if v, ok := _c.mutation.Completeness(); ok {
		if err := resource.CompletenessValidator(v); err != nil {
			return &ValidationError{Name: "completeness", err: fmt.Errorf(`ent: validator failed for field "Resource.completeness": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Resource.created_at"`)}
	}
	return nil
}

func (_c *ResourceCreate) sqlSave(ctx context.Context) (*Resource, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ResourceCreate) createSpec() (*Resource, *sqlgraph.CreateSpec) {
	var (
		_node = &Resource{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(resource.Table, sqlgraph.NewFieldSpec(resource.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.AstraID(); ok {
		_spec.SetField(resource.FieldAstraID, field.TypeString, value)
		_node.AstraID = value
	}
	if value, ok := _c.mutation.GetType(); ok {
		_spec.SetField(resource.FieldType, field.TypeString, value)
		_node.Type = value
	}
	if value, ok := _c.mutation.URI(); ok {
		_spec.SetField(resource.FieldURI, field.TypeString, value)
		_node.URI = value
	}
	if value, ok := _c.mutation.Format(); ok {
		_spec.SetField(resource.FieldFormat, field.TypeString, value)
		_node.Format = value
	}
	if value, ok := _c.mutation.Metadata(); ok {
		_spec.SetField(resource.FieldMetadata, field.TypeJSON, value)
		_node.Metadata = value
	}
	if value, ok := _c.mutation.Completeness(); ok {
		_spec.SetField(resource.FieldCompleteness, field.TypeEnum, value)
		_node.Completeness = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(resource.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	return _node, _spec
}

// ResourceCreateBulk is the builder for creating many Resource entities in bulk.
type ResourceCreateBulk struct {
	config
	err      error
	builders []*ResourceCreate
}

// Save creates the Resource entities in the database.
func (_c *ResourceCreateBulk) Save(ctx context.Context) ([]*Resource, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Resource, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ResourceMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ResourceCreateBulk) SaveX(ctx context.Context) []*Resource {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ResourceCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ResourceCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
