// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/TSELab/astra/internal/store/ent/predicate"
	"github.com/TSELab/astra/internal/store/ent/resource"
)

// ResourceUpdate is the builder for updating Resource entities.
type ResourceUpdate struct {
	config
	hooks    []Hook
	mutation *ResourceMutation
}

// Where appends a list predicates to the ResourceUpdate builder.
func (_u *ResourceUpdate) Where(ps ...predicate.Resource) *ResourceUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetAstraID sets the "astra_id" field.
func (_u *ResourceUpdate) SetAstraID(v string) *ResourceUpdate {
	_u.mutation.SetAstraID(v)
	return _u
}

// SetNillableAstraID sets the "astra_id" field if the given value is not nil.
func (_u *ResourceUpdate) SetNillableAstraID(v *string) *ResourceUpdate {
	if v != nil {
		_u.SetAstraID(*v)
	}
	return _u
}

// SetType sets the "type" field.
func (_u *ResourceUpdate) SetType(v string) *ResourceUpdate {
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *ResourceUpdate) SetNillableType(v *string) *ResourceUpdate {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// SetURI sets the "uri" field.
func (_u *ResourceUpdate) SetURI(v string) *ResourceUpdate {
	_u.mutation.SetURI(v)
	return _u
}

// SetNillableURI sets the "uri" field if the given value is not nil.
func (_u *ResourceUpdate) SetNillableURI(v *string) *ResourceUpdate {
	if v != nil {
		_u.SetURI(*v)
	}
	return _u
}

// SetFormat sets the "format" field.
func (_u *ResourceUpdate) SetFormat(v string) *ResourceUpdate {
	_u.mutation.SetFormat(v)
	return _u
}

// SetNillableFormat sets the "format" field if the given value is not nil.
func (_u *ResourceUpdate) SetNillableFormat(v *string) *ResourceUpdate {
	if v != nil {
		_u.SetFormat(*v)
	}
	return _u
}

// SetMetadata sets the "metadata" field.
func (_u *ResourceUpdate) SetMetadata(v map[string]string) *ResourceUpdate {
	_u.mutation.SetMetadata(v)
	return _u
}

// ClearMetadata clears the value of the "metadata" field.
func (_u *ResourceUpdate) ClearMetadata() *ResourceUpdate {
	_u.mutation.ClearMetadata()
	return _u
}

// SetCompleteness sets the "completeness" field.
func (_u *ResourceUpdate) SetCompleteness(v resource.Completeness) *ResourceUpdate {
	_u.mutation.SetCompleteness(v)
	return _u
}

// SetNillableCompleteness sets the "completeness" field if the given value is not nil.
func (_u *ResourceUpdate) SetNillableCompleteness(v *resource.Completeness) *ResourceUpdate {
	if v != nil {
		_u.SetCompleteness(*v)
	}
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *ResourceUpdate) SetCreatedAt(v time.Time) *ResourceUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *ResourceUpdate) SetNillableCreatedAt(v *time.Time) *ResourceUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// Mutation returns the ResourceMutation object of the builder.
func (_u *ResourceUpdate) Mutation() *ResourceMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ResourceUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ResourceUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ResourceUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ResourceUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ResourceUpdate) check() error {
	if v, ok := _u.mutation.AstraID(); ok {
		if err := resource.AstraIDValidator(v); err != nil {
			return &ValidationError{Name: "astra_id", err: fmt.Errorf(`ent: validator failed for field "Resource.astra_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Completeness(); ok {
		if err := resource.CompletenessValidator(v); err != nil {
			return &ValidationError{Name: "completeness", err: fmt.Errorf(`ent: validator failed for field "Resource.completeness": %w`, err)}
		}
	}
	return nil
}

func (_u *ResourceUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(resource.Table, resource.Columns, sqlgraph.NewFieldSpec(resource.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.AstraID(); ok {
		_spec.SetField(resource.FieldAstraID, field.TypeString, value)
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(resource.FieldType, field.TypeString, value)
	}
	if value, ok := _u.mutation.URI(); ok {
		_spec.SetField(resource.FieldURI, field.TypeString, value)
	}
	if value, ok := _u.mutation.Format(); ok {
		_spec.SetField(resource.FieldFormat, field.TypeString, value)
	}
	if value, ok := _u.mutation.Metadata(); ok {
		_spec.SetField(resource.FieldMetadata, field.TypeJSON, value)
	}
	if _u.mutation.MetadataCleared() {
		_spec.ClearField(resource.FieldMetadata, field.TypeJSON)
	}
	if value, ok := _u.mutation.Completeness(); ok {
		_spec.SetField(resource.FieldCompleteness, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(resource.FieldCreatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{resource.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ResourceUpdateOne is the builder for updating a single Resource entity.
type ResourceUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ResourceMutation
}

// SetAstraID sets the "astra_id" field.
func (_u *ResourceUpdateOne) SetAstraID(v string) *ResourceUpdateOne {
	_u.mutation.SetAstraID(v)
	return _u
}

// SetNillableAstraID sets the "astra_id" field if the given value is not nil.
func (_u *ResourceUpdateOne) SetNillableAstraID(v *string) *ResourceUpdateOne {
	if v != nil {
		_u.SetAstraID(*v)
	}
	return _u
}

// SetType sets the "type" field.
func (_u *ResourceUpdateOne) SetType(v string) *ResourceUpdateOne {
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *ResourceUpdateOne) SetNillableType(v *string) *ResourceUpdateOne {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// SetURI sets the "uri" field.
func (_u *ResourceUpdateOne) SetURI(v string) *ResourceUpdateOne {
	_u.mutation.SetURI(v)
	return _u
}

// SetNillableURI sets the "uri" field if the given value is not nil.
func (_u *ResourceUpdateOne) SetNillableURI(v *string) *ResourceUpdateOne {
	if v != nil {
		_u.SetURI(*v)
	}
	return _u
}

// SetFormat sets the "format" field.
func (_u *ResourceUpdateOne) SetFormat(v string) *ResourceUpdateOne {
	_u.mutation.SetFormat(v)
	return _u
}

// SetNillableFormat sets the "format" field if the given value is not nil.
func (_u *ResourceUpdateOne) SetNillableFormat(v *string) *ResourceUpdateOne {
	if v != nil {
		_u.SetFormat(*v)
	}
	return _u
}

// SetMetadata sets the "metadata" field.
func (_u *ResourceUpdateOne) SetMetadata(v map[string]string) *ResourceUpdateOne {
	_u.mutation.SetMetadata(v)
	return _u
}

// ClearMetadata clears the value of the "metadata" field.
func (_u *ResourceUpdateOne) ClearMetadata() *ResourceUpdateOne {
	_u.mutation.ClearMetadata()
	return _u
}

// SetCompleteness sets the "completeness" field.
func (_u *ResourceUpdateOne) SetCompleteness(v resource.Completeness) *ResourceUpdateOne {
	_u.mutation.SetCompleteness(v)
	return _u
}

// SetNillableCompleteness sets the "completeness" field if the given value is not nil.
func (_u *ResourceUpdateOne) SetNillableCompleteness(v *resource.Completeness) *ResourceUpdateOne {
	if v != nil {
		_u.SetCompleteness(*v)
	}
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *ResourceUpdateOne) SetCreatedAt(v time.Time) *ResourceUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *ResourceUpdateOne) SetNillableCreatedAt(v *time.Time) *ResourceUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// Mutation returns the ResourceMutation object of the builder.
func (_u *ResourceUpdateOne) Mutation() *ResourceMutation {
	return _u.mutation
}

// Where appends a list predicates to the ResourceUpdate builder.
func (_u *ResourceUpdateOne) Where(ps ...predicate.Resource) *ResourceUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ResourceUpdateOne) Select(field string, fields ...string) *ResourceUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Resource entity.
func (_u *ResourceUpdateOne) Save(ctx context.Context) (*Resource, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ResourceUpdateOne) SaveX(ctx context.Context) *Resource {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ResourceUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ResourceUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ResourceUpdateOne) check() error {
	if v, ok := _u.mutation.AstraID(); ok {
		if err := resource.AstraIDValidator(v); err != nil {
			return &ValidationError{Name: "astra_id", err: fmt.Errorf(`ent: validator failed for field "Resource.astra_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Completeness(); ok {
		if err := resource.CompletenessValidator(v); err != nil {
			return &ValidationError{Name: "completeness", err: fmt.Errorf(`ent: validator failed for field "Resource.completeness": %w`, err)}
		}
	}
	return nil
}

func (_u *ResourceUpdateOne) sqlSave(ctx context.Context) (_node *Resource, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(resource.Table, resource.Columns, sqlgraph.NewFieldSpec(resource.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Resource.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, resource.FieldID)
		for _, f := range fields {
			if !resource.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != resource.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.AstraID(); ok {
		_spec.SetField(resource.FieldAstraID, field.TypeString, value)
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(resource.FieldType, field.TypeString, value)
	}
	if value, ok := _u.mutation.URI(); ok {
		_spec.SetField(resource.FieldURI, field.TypeString, value)
	}
	if value, ok := _u.mutation.Format(); ok {
		_spec.SetField(resource.FieldFormat, field.TypeString, value)
	}
	if value, ok := _u.mutation.Metadata(); ok {
		_spec.SetField(resource.FieldMetadata, field.TypeJSON, value)
	}
	if _u.mutation.MetadataCleared() {
		_spec.ClearField(resource.FieldMetadata, field.TypeJSON)
	}
	if value, ok := _u.mutation.Completeness(); ok {
		_spec.SetField(resource.FieldCompleteness, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(resource.FieldCreatedAt, field.TypeTime, value)
	}
	_node = &Resource{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{resource.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
