// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/TSELab/astra/internal/store/ent/artifact"
	"github.com/TSELab/astra/internal/store/ent/principal"
	"github.com/TSELab/astra/internal/store/ent/resource"
	"github.com/TSELab/astra/internal/store/ent/schema"
	"github.com/TSELab/astra/internal/store/ent/step"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	artifactFields := schema.Artifact{}.Fields()
	_ = artifactFields
	// artifactDescAstraID is the schema descriptor for astra_id field.
	artifactDescAstraID := artifactFields[0].Descriptor()
	// artifact.AstraIDValidator is a validator for the "astra_id" field. It is called by the builders before save.
	artifact.AstraIDValidator = artifactDescAstraID.Validators[0].(func(string) error)
	// artifactDescName is the schema descriptor for name field.
	artifactDescName := artifactFields[1].Descriptor()
	// artifact.DefaultName holds the default value on creation for the name field.
	artifact.DefaultName = artifactDescName.Default.(string)
	// artifactDescKind is the schema descriptor for kind field.
	artifactDescKind := artifactFields[2].Descriptor()
	// artifact.DefaultKind holds the default value on creation for the kind field.
	artifact.DefaultKind = artifactDescKind.Default.(string)
	// artifactDescURI is the schema descriptor for uri field.
	artifactDescURI := artifactFields[3].Descriptor()
	// artifact.DefaultURI holds the default value on creation for the uri field.
	artifact.DefaultURI = artifactDescURI.Default.(string)
	// artifactDescVersion is the schema descriptor for version field.
	artifactDescVersion := artifactFields[4].Descriptor()
	// artifact.DefaultVersion holds the default value on creation for the version field.
	artifact.DefaultVersion = artifactDescVersion.Default.(string)
	// artifactDescHash is the schema descriptor for hash field.
	artifactDescHash := artifactFields[5].Descriptor()
	// artifact.DefaultHash holds the default value on creation for the hash field.
	artifact.DefaultHash = artifactDescHash.Default.(string)
	// artifactDescSize is the schema descriptor for size field.
	artifactDescSize := artifactFields[6].Descriptor()
	// artifact.DefaultSize holds the default value on creation for the size field.
	artifact.DefaultSize = artifactDescSize.Default.(int64)
	// artifactDescCreatedAt is the schema descriptor for created_at field.
	artifactDescCreatedAt := artifactFields[9].Descriptor()
	// artifact.DefaultCreatedAt holds the default value on creation for the created_at field.
	artifact.DefaultCreatedAt = artifactDescCreatedAt.Default.(func() time.Time)
	principalFields := schema.Principal{}.Fields()
	_ = principalFields
	// principalDescAstraID is the schema descriptor for astra_id field.
	principalDescAstraID := principalFields[0].Descriptor()
	// principal.AstraIDValidator is a validator for the "astra_id" field. It is called by the builders before save.
	principal.AstraIDValidator = principalDescAstraID.Validators[0].(func(string) error)
	// principalDescName is the schema descriptor for name field.
	principalDescName := principalFields[1].Descriptor()
	// principal.DefaultName holds the default value on creation for the name field.
	principal.DefaultName = principalDescName.Default.(string)
	// principalDescTrust is the schema descriptor for trust field.
	principalDescTrust := principalFields[2].Descriptor()
	// principal.DefaultTrust holds the default value on creation for the trust field.
	principal.DefaultTrust = principalDescTrust.Default.(string)
	// principalDescBuilder is the schema descriptor for builder field.
	principalDescBuilder := principalFields[3].Descriptor()
	// principal.DefaultBuilder holds the default value on creation for the builder field.
	principal.DefaultBuilder = principalDescBuilder.Default.(string)
	// principalDescCreatedAt is the schema descriptor for created_at field.
	principalDescCreatedAt := principalFields[6].Descriptor()
	// principal.DefaultCreatedAt holds the default value on creation for the created_at field.
	principal.DefaultCreatedAt = principalDescCreatedAt.Default.(func() time.Time)
	resourceFields := schema.Resource{}.Fields()
	_ = resourceFields
	// resourceDescAstraID is the schema descriptor for astra_id field.
	resourceDescAstraID := resourceFields[0].Descriptor()
	// resource.AstraIDValidator is a validator for the "astra_id" field. It is called by the builders before save.
	resource.AstraIDValidator = resourceDescAstraID.Validators[0].(func(string) error)
	// resourceDescType is the schema descriptor for type field.
	resourceDescType := resourceFields[1].Descriptor()
	// resource.DefaultType holds the default value on creation for the type field.
	resource.DefaultType = resourceDescType.Default.(string)
	// resourceDescURI is the schema descriptor for uri field.
	resourceDescURI := resourceFields[2].Descriptor()
	// resource.DefaultURI holds the default value on creation for the uri field.
	resource.DefaultURI = resourceDescURI.Default.(string)
	// resourceDescFormat is the schema descriptor for format field.
	resourceDescFormat := resourceFields[3].Descriptor()
	// resource.DefaultFormat holds the default value on creation for the format field.
	resource.DefaultFormat = resourceDescFormat.Default.(string)
	// resourceDescCreatedAt is the schema descriptor for created_at field.
	resourceDescCreatedAt := resourceFields[6].Descriptor()
	// resource.DefaultCreatedAt holds the default value on creation for the created_at field.
	resource.DefaultCreatedAt = resourceDescCreatedAt.Default.(func() time.Time)
	stepFields := schema.Step{}.Fields()
	_ = stepFields
	// stepDescAstraID is the schema descriptor for astra_id field.
	stepDescAstraID := stepFields[0].Descriptor()
	// step.AstraIDValidator is a validator for the "astra_id" field. It is called by the builders before save.
	step.AstraIDValidator = stepDescAstraID.Validators[0].(func(string) error)
	// stepDescCommand is the schema descriptor for command field.
	stepDescCommand := stepFields[1].Descriptor()
	// step.DefaultCommand holds the default value on creation for the command field.
	step.DefaultCommand = stepDescCommand.Default.(string)
	// stepDescArch is the schema descriptor for Arch field.
	stepDescArch := stepFields[3].Descriptor()
	// step.DefaultArch holds the default value on creation for the Arch field.
	step.DefaultArch = stepDescArch.Default.(string)
	// stepDescCreatedAt is the schema descriptor for created_at field.
	stepDescCreatedAt := stepFields[7].Descriptor()
	// step.DefaultCreatedAt holds the default value on creation for the created_at field.
	step.DefaultCreatedAt = stepDescCreatedAt.Default.(func() time.Time)
}
