// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/TSELab/astra/internal/store/ent/step"
)

// Step is the model entity for the Step schema.
type Step struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// unique AStRA step ID
	AstraID string `json:"astra_id,omitempty"`
	// Command holds the value of the "command" field.
	Command string `json:"command,omitempty"`
	// Environment holds the value of the "environment" field.
	Environment map[string]string `json:"environment,omitempty"`
	// Optional higher-level grouping: source, build, review, package
	Arch string `json:"Arch,omitempty"`
	// Timestamp holds the value of the "timestamp" field.
	Timestamp string `json:"timestamp,omitempty"`
	// Metadata holds the value of the "metadata" field.
	Metadata map[string]string `json:"metadata,omitempty"`
	// Completeness holds the value of the "completeness" field.
	Completeness step.Completeness `json:"completeness,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt    time.Time `json:"created_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Step) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case step.FieldEnvironment, step.FieldMetadata:
			values[i] = new([]byte)
		case step.FieldID:
			values[i] = new(sql.NullInt64)
		case step.FieldAstraID, step.FieldCommand, step.FieldArch, step.FieldTimestamp, step.FieldCompleteness:
			values[i] = new(sql.NullString)
		case step.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Step fields.
func (_m *Step) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case step.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case step.FieldAstraID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field astra_id", values[i])
			} else if value.Valid {
				_m.AstraID = value.String
			}
		case step.FieldCommand:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field command", values[i])
			} else if value.Valid {
				_m.Command = value.String
			}
		case step.FieldEnvironment:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field environment", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Environment); err != nil {
					return fmt.Errorf("unmarshal field environment: %w", err)
				}
			}
		case step.FieldArch:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field Arch", values[i])
			} else if value.Valid {
				_m.Arch = value.String
			}
		case step.FieldTimestamp:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field timestamp", values[i])
			} else if value.Valid {
				_m.Timestamp = value.String
			}
		case step.FieldMetadata:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field metadata", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Metadata); err != nil {
					return fmt.Errorf("unmarshal field metadata: %w", err)
				}
			}
		case step.FieldCompleteness:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field completeness", values[i])
			} else if value.Valid {
				_m.Completeness = step.Completeness(value.String)
			}
		case step.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Step.
// This includes values selected through modifiers, order, etc.
func (_m *Step) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this Step.
// Note that you need to call Step.Unwrap() before calling this method if this Step
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Step) Update() *StepUpdateOne {
	return NewStepClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Step entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Step) Unwrap() *Step {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Step is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Step) String() string {
	var builder strings.Builder
	builder.WriteString("Step(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("astra_id=")
	builder.WriteString(_m.AstraID)
	builder.WriteString(", ")
	builder.WriteString("command=")
	builder.WriteString(_m.Command)
	builder.WriteString(", ")
	builder.WriteString("environment=")
	builder.WriteString(fmt.Sprintf("%v", _m.Environment))
	builder.WriteString(", ")
	builder.WriteString("Arch=")
	builder.WriteString(_m.Arch)
	builder.WriteString(", ")
	builder.WriteString("timestamp=")
	builder.WriteString(_m.Timestamp)
	builder.WriteString(", ")
	builder.WriteString("metadata=")
	builder.WriteString(fmt.Sprintf("%v", _m.Metadata))
	builder.WriteString(", ")
	builder.WriteString("completeness=")
	builder.WriteString(fmt.Sprintf("%v", _m.Completeness))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Steps is a parsable slice of Step.
type Steps []*Step
