// Code generated by ent, DO NOT EDIT.

package artifact

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the artifact type in the database.
	Label = "artifact"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldAstraID holds the string denoting the astra_id field in the database.
	FieldAstraID = "astra_id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldKind holds the string denoting the kind field in the database.
	FieldKind = "kind"
	// FieldURI holds the string denoting the uri field in the database.
	FieldURI = "uri"
	// FieldVersion holds the string denoting the version field in the database.
	FieldVersion = "version"
	// FieldHash holds the string denoting the hash field in the database.
	FieldHash = "hash"
	// FieldSize holds the string denoting the size field in the database.
	FieldSize = "size"
	// FieldMetadata holds the string denoting the metadata field in the database.
	FieldMetadata = "metadata"
	// FieldCompleteness holds the string denoting the completeness field in the database.
	FieldCompleteness = "completeness"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// Table holds the table name of the artifact in the database.
	Table = "artifacts"
)

// Columns holds all SQL columns for artifact fields.
var Columns = []string{
	FieldID,
	FieldAstraID,
	FieldName,
	FieldKind,
	FieldURI,
	FieldVersion,
	FieldHash,
	FieldSize,
	FieldMetadata,
	FieldCompleteness,
	FieldCreatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// AstraIDValidator is a validator for the "astra_id" field. It is called by the builders before save.
	AstraIDValidator func(string) error
	// DefaultName holds the default value on creation for the "name" field.
	DefaultName string
	// DefaultKind holds the default value on creation for the "kind" field.
	DefaultKind string
	// DefaultURI holds the default value on creation for the "uri" field.
	DefaultURI string
	// DefaultVersion holds the default value on creation for the "version" field.
	DefaultVersion string
	// DefaultHash holds the default value on creation for the "hash" field.
	DefaultHash string
	// DefaultSize holds the default value on creation for the "size" field.
	DefaultSize int64
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
)

// Completeness defines the type for the "completeness" enum field.
type Completeness string

// CompletenessComplete is the default value of the Completeness enum.
const DefaultCompleteness = CompletenessComplete

// Completeness values.
const (
	CompletenessComplete   Completeness = "complete"
	CompletenessIncomplete Completeness = "incomplete"
)

func (c Completeness) String() string {
	return string(c)
}

// CompletenessValidator is a validator for the "completeness" field enum values. It is called by the builders before save.
func CompletenessValidator(c Completeness) error {
	switch c {
	case CompletenessComplete, CompletenessIncomplete:
		return nil
	default:
		return fmt.Errorf("artifact: invalid enum value for completeness field: %q", c)
	}
}

// OrderOption defines the ordering options for the Artifact queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByAstraID orders the results by the astra_id field.
func ByAstraID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAstraID, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByKind orders the results by the kind field.
func ByKind(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldKind, opts...).ToFunc()
}

// ByURI orders the results by the uri field.
func ByURI(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldURI, opts...).ToFunc()
}

// ByVersion orders the results by the version field.
func ByVersion(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldVersion, opts...).ToFunc()
}

// ByHash orders the results by the hash field.
func ByHash(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldHash, opts...).ToFunc()
}

// BySize orders the results by the size field.
func BySize(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSize, opts...).ToFunc()
}

// ByCompleteness orders the results by the completeness field.
func ByCompleteness(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCompleteness, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}
