// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Artifact is the predicate function for artifact builders.
type Artifact func(*sql.Selector)

// Edge is the predicate function for edge builders.
type Edge func(*sql.Selector)

// Principal is the predicate function for principal builders.
type Principal func(*sql.Selector)

// Resource is the predicate function for resource builders.
type Resource func(*sql.Selector)

// Step is the predicate function for step builders.
type Step func(*sql.Selector)
